pipeline{
  agent any

  stages{
      stage("Checkout"){
         steps {
            checkout scm
               }
              }

         stage("Build"){
                  steps {
                     sh './gradlew clean build'
                        }
                       }


                      }
         }


# Generated by Docker Engine.
# This file can be edited; Docker Engine will not make further changes once it
# has been modified.

nameserver 127.0.0.11
search tail8366a0.ts.net
options ndots:0

# Based on host file: '/etc/resolv.conf' (internal resolver)
# ExtServers: [host(10.255.255.254)]
# Overrides: []
# Option ndots from: internal